version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    restart: always # 出错则重启
    privileged: true # 高权限，执行下面的 mysql/init
    volumes:
      - /Users/ooyang/Desktop/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/ooyang/Desktop/redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
